name: deploy
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for Workload Identity Federation

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          # Option 1: Workload Identity Federation
          #workload_identity_provider: 'projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID'
          #service_account: 'my-service-account@PROJECT_ID.iam.gserviceaccount.com'
          # Option 2: Service Account Key (less recommended for production)
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: stock-peer-00002-h4t
          image: ${{ secrets.DOCKER_USERNAME }}/stock_peer:latest
          region: us-central1 # Replace with your Cloud Run region