name: build_and_push
on: push
jobs:
   docker-build:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            #registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: checkout
          uses: actions/checkout@v4
        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: docker.io/${{ env.DOCKER_USERNAME }}/stock_peer:latest # Using tags from metadata-action
            #labels: ${{ steps.meta.outputs.labels }} # Using labels from metadata-action
