name: build_and_push
on: push
jobs:
   docker-build:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.REPO_TOKEN }}
        - name: checkout
          uses: actions/checkout@v4
        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: ghcr.io/ajoupyterhub/stock_peer:latest # Using tags from metadata-action
            #labels: ${{ steps.meta.outputs.labels }} # Using labels from metadata-action
